-- Disable RLS on all tables to allow unrestricted access for single-user mode
ALTER TABLE income_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE daily_data DISABLE ROW LEVEL SECURITY;
ALTER TABLE goals DISABLE ROW LEVEL SECURITY;
ALTER TABLE fixed_expenses DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_plans DISABLE ROW LEVEL SECURITY;
ALTER TABLE payment_plan_payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings DISABLE ROW LEVEL SECURITY;
